---
servers:
  - localhost:9060
  - localhost:9061
  - localhost:9062
  - remoteMachine@ipaddress:portNumber
filepaths:
  - path/to/goaway/library
modules:
  - nameOfApplicationModule /path/to/applicationModule
